json_bachelor_accreditation = [
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта: Англійська мова і література",
        "educational_program_name": "Англійська мова та зарубіжна література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495138",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Біологія та здоров'я людини)",
        "educational_program_name": "Біологія та здоров’я людини",
        "accreditation_description": "Сертифікат про акредитацію спеціальності УД 04009183",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Географія)",
        "educational_program_name": "Географія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495143",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Історія)",
        "educational_program_name": "Історія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495139",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Математика)",
        "educational_program_name": "Математика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495140",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта: Українська мова і література",
        "educational_program_name": "Українська мова і література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495137",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Фізика)",
        "educational_program_name": "Фізика та астрономія",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Хімія)",
        "educational_program_name": "Хімія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495142",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "016",
        "speciality_name": "Спеціальна освіта",
        "speciality_specialization": "Спеціальна освіта: логопедія та олігофренопедагогіка",
        "educational_program_name": "Логопедія",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "022",
        "speciality_name": "Дизайн",
        "speciality_specialization": "Дизайн",
        "educational_program_name": "Графічний дизайн",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495145",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "023",
        "speciality_name": "Образотворче мистецтво, декоративне мистецтво, реставрація",
        "speciality_specialization": "Образотворче та декоративне мистецтво",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495146",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "029",
        "speciality_name": "Інформаційна, бібліотечна та архівна справа",
        "speciality_specialization": "Диджитальні медіа",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "031",
        "speciality_name": "Релігієзнавство",
        "speciality_specialization": "Релігієзнавство",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495147",
        "accrediation_end": "01.07.2027",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "speciality_specialization": "Європейські студії та американістика",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495148",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "speciality_specialization": "Історія та археологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495148",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "speciality_specialization": "Історична україністика та прикладна історія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495148",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "033",
        "speciality_name": "Філософія",
        "speciality_specialization": "Філософія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495149",
        "accrediation_end": "01.07.2027",
    },
    {
        "speciality_code": "034",
        "speciality_name": "Культурологія",
        "speciality_specialization": "Культурологія: менеджмент культурних процесів",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Англійська та друга західноєвропейська мови і літератури",
        "educational_program_name": "германські мови та літератури (переклад включно), перша - англійська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Переклад з англійської та німецької мов",
        "educational_program_name": "германські мови та літератури (переклад включно), перша - англійська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Німецька та англійська мови і літератури",
        "educational_program_name": "германські мови та літератури (переклад включно), перша - німецька",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Прикладна лінгвістика",
        "educational_program_name": "прикладна лінгвістика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Французька та англійська мови і літератури",
        "educational_program_name": "романські мови та літератури (переклад включно), перша - французька",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Польська мова та література",
        "educational_program_name": "слов’янські мови та літератури (переклад включно), перша - польська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Китайська та англійська мови і літератури",
        "educational_program_name": "східні мови та літератури (переклад включно), перша - китайська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Японська та англійська мови і літератури",
        "educational_program_name": "східні мови та літератури (переклад включно), перша - японська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Українська мова та література",
        "educational_program_name": "українська мова та література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "speciality_specialization": "Бізнес-аналітика",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495151",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "speciality_specialization": "Цифрова й інформаційна економіка",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495151",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "speciality_specialization": "Політична соціологія та політичний менеджмент",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495152",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "speciality_specialization": "Політологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495152",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "speciality_specialization": "Практична психологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495153",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "speciality_specialization": "Психологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495153",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "054",
        "speciality_name": "Соціологія",
        "speciality_specialization": "Соціологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495154",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "speciality_specialization": "Журналістика",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495157",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "speciality_specialization": "Реклама і зв’язки з громадськістю",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495157",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "071",
        "speciality_name": "Облік і оподаткування",
        "speciality_specialization": "Бізнес-консалтинг",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495158",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "speciality_specialization": "Міжнародний менеджмент",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495160",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "075",
        "speciality_name": "Маркетинг",
        "speciality_specialization": "Маркетинг",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1720",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "076",
        "speciality_name": "Підприємництво та торгівля",
        "speciality_specialization": "Економіка підприємства та організація бізнесу",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "081",
        "speciality_name": "Право",
        "speciality_specialization": "Право",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495163",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "speciality_specialization": "Біоінформатика",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "speciality_specialization": "Біорізноманіття та ландшафтний дизайн",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "speciality_specialization": "Біохімія та фізіологія",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "speciality_specialization": "Мікробіологія та вірусологія",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "speciality_specialization": "Системна біологія та гідробіоресурси",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Екологія",
        "speciality_specialization": "Екологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495165",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Хімія",
        "speciality_specialization": "Хімічний аналіз та експертиза матеріалів та виробів",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495166",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Хімія",
        "speciality_specialization": "Хімія лікарських речовин",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495166",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "103",
        "speciality_name": "Науки про Землю",
        "speciality_specialization": "Геоекологічний інжиніринг",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495167",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "104",
        "speciality_name": "Фізика та астрономія",
        "speciality_specialization": "Фізика та астрономія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495168",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "105",
        "speciality_name": "Прикладна фізика та наноматеріали",
        "speciality_specialization": "Радіофізика, електроніка та оптоінформатика",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495169",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "106",
        "speciality_name": "Географія",
        "speciality_specialization": "Географія рекреації та туризму",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accrediation_end": "30.05.2024",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика",
        "speciality_specialization": "Математика",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495170",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика",
        "speciality_specialization": "Математика інтелектуальних систем",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495170",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "112",
        "speciality_name": "Статистика",
        "speciality_specialization": "Статистика",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495171",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "speciality_specialization": "Комп'ютерне моделювання та технології програмування",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "speciality_specialization": "Комп’ютерний інжиніринг безпілотних літальних апаратів і комплексів",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "speciality_specialization": "Облік, аналітика та моделювання бізнес-систем",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "speciality_specialization": "Прикладне комп'ютерне та математичне моделювання",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "121",
        "speciality_name": "Інженерія програмного забезпечення",
        "speciality_specialization": "Інженерія програмного забезпечення",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495173",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "122",
        "speciality_name": "Комп'ютерні науки",
        "speciality_specialization": "Комп'ютерні науки",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495244",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "123",
        "speciality_name": "Комп’ютерна інженерія",
        "speciality_specialization": "Комп’ютерна інженерія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495175",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "124",
        "speciality_name": "Системний аналіз",
        "speciality_specialization": "Системний аналіз",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495176",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "125",
        "speciality_name": "Кібербезпека та захист інформації",
        "speciality_specialization": "Кібербезпека та системи технічного захисту",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "126",
        "speciality_name": "Інформаційні системи та технології",
        "speciality_specialization": "Інформаційні системи та технології",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accrediation_end": "30.05.2024",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "speciality_specialization": "Інжиніринг механотронних і робототехнічних систем",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495178",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "speciality_specialization": "Комп'ютерні технології інженерії міцності",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495178",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "132",
        "speciality_name": "Матеріалознавство",
        "speciality_specialization": "Матеріалознавство",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495179",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "133",
        "speciality_name": "Галузеве машинобудування",
        "speciality_specialization": "Галузеве машинобудування",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495180",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "133",
        "speciality_name": "Галузеве машинобудування",
        "speciality_specialization": "Комп'ютерний інжиніринг і технології автоматизованих виробництв",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495180",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "speciality_specialization": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495181",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "speciality_specialization": "Проєктування, виробництво та експлуатація безпілотних систем і комплексів",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495181",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "speciality_specialization": "Ракетні двигуни",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495181",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "141",
        "speciality_name": "Електроенергетика, електротехніка та електромеханіка",
        "speciality_specialization": "Відновлювані джерела енергії та енергоефективні технології",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495182",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "144",
        "speciality_name": "Теплоенергетика",
        "speciality_specialization": "Теплоенергетика",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495183",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "161",
        "speciality_name": "Хімічні технології та інженерія",
        "speciality_specialization": "Хімічні технології та інженерія",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "162",
        "speciality_name": "Біотехнології та біоінженерія",
        "speciality_specialization": "Біотехнології та біоінженерія",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "172",
        "speciality_name": "Електронні комунікації та радіотехніка",
        "speciality_specialization": "Інфокомунікації та системи зв’язку",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "174",
        "speciality_name": "Автоматизація, комп’ютерно-інтегровані технології та робототехніка",
        "speciality_specialization": "Автоматизація та комп`ютерно-інтегровані технології",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "181",
        "speciality_name": "Харчові технології",
        "speciality_specialization": "Ресторанні та крафтові технології здорового харчування",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "183",
        "speciality_name": "Технології захисту навколишнього середовища",
        "speciality_specialization": "Екоаналітика та техногенна безпека",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "223",
        "speciality_name": "Медсестринство",
        "speciality_specialization": "Медсестринство",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1719",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "224",
        "speciality_name": "Технології медичної діагностики та лікування",
        "speciality_specialization": "Технології медичної діагностики та лікування",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495191",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "176",
        "speciality_name": "Мікро- та наносистемна техніка",
        "speciality_specialization": "Мікро- та наносистемна техніка",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності УД 04017903",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "181",
        "speciality_name": "Харчові технології",
        "speciality_specialization": "Харчові технології",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1712",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "227",
        "speciality_name": "Терапія та реабілітація",
        "speciality_specialization": "Фізична терапія, ерготерапія",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "229",
        "speciality_name": "Громадське здоров`я",
        "speciality_specialization": "",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "231",
        "speciality_name": "Соціальна робота",
        "speciality_specialization": "",
        "educational_program_name": "Соціальна робота",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495192",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "241",
        "speciality_name": "Готельно-ресторанна справа",
        "speciality_specialization": "",
        "educational_program_name": "Готельно-ресторанна справа",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "242",
        "speciality_name": "Туризм і рекреація",
        "speciality_specialization": "Міжнародний туризм",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "281",
        "speciality_name": "Публічне управління та адміністрування",
        "speciality_specialization": "Публічне управління, медіація, електронне врядування",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "291",
        "speciality_name": "Міжнародні відносини",
        "speciality_specialization": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "educational_program_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accrediation_end": "30.05.2024",
    },
    {
        "speciality_code": "292",
        "speciality_name": "Міжнародні відносини",
        "speciality_specialization": "Міжнародні економічні відносини",
        "educational_program_name": "Міжнародна економіка",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495243",
        "accrediation_end": "01.07.2025",
    },
]

json_master_accreditation = [
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Біологія та здоров'я людини)",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1187",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Географія)",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1140",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Історія)",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 3966",
        "accrediation_end": "01.07.2028",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Середня освіта (Математика)",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 124",
        "accrediation_end": "28.01.2025",
    },
    {
        "speciality_code": "016",
        "speciality_name": "Спеціальна освіта",
        "speciality_specialization": "Логопедія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495201",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "022",
        "speciality_name": "Дизайн",
        "speciality_specialization": "Дизайн візуального середовища",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 129",
        "accrediation_end": "28.01.2025",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "speciality_specialization": "Історія та археологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010057",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "033",
        "speciality_name": "Філософія",
        "speciality_specialization": "Філософія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003209",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "029",
        "speciality_name": "Інформаційна, бібліотечна та архівна справа",
        "speciality_specialization": "Менеджмент інформаційної діяльності",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Англійська та друга західноєвропейська мови і літератури",
        "educational_program_name": "германські мови та літератури (переклад включно), перша - англійська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Переклад з англійської та німецької мов",
        "educational_program_name": "германські мови та літератури (переклад включно), перша - англійська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Німецька та англійська мови і літератури",
        "educational_program_name": "германські мови та літератури (переклад включно), перша - німецька",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Французька та англійська мови і літератури",
        "educational_program_name": "романські мови та літератури (переклад включно), перша - французька",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Китайська та англійська мови і літератури",
        "educational_program_name": "східні мови та літератури (переклад включно), перша - китайська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Японська та англійська мови і літератури",
        "educational_program_name": "східні мови та літератури (переклад включно), перша - японська",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Українська мова та література",
        "educational_program_name": "українська мова та література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "speciality_specialization": "Бізнес-аналітика та інформаційна безпека",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010058",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "speciality_specialization": "Політологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010059",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "speciality_specialization": "Кризова та реабілітаційна психологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495247",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "speciality_specialization": "Психологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010060",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "speciality_specialization": "Психологія управління",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495247",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "054",
        "speciality_name": "Соціологія",
        "speciality_specialization": "Соціологія",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003210",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "speciality_specialization": "Медіакомунікації",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010061",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "speciality_specialization": "Реклама і зв`язки з громадськістю",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010063",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "071",
        "speciality_name": "Облік і оподаткування",
        "speciality_specialization": "Облік і оподаткування",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007573",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "speciality_specialization": "Бізнес-адміністрування",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495213",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "speciality_specialization": "Міжнародний менеджмент",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495213",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "075",
        "speciality_name": "Маркетинг",
        "speciality_specialization": "Маркетинг",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007575",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "076",
        "speciality_name": "Підприємництво та торгівля",
        "speciality_specialization": "Економіка підприємства та управління бізнесом",
        "educational_program_name": "",
        "accreditation_description": "",
        "accreditation_end": "",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "speciality_specialization": "Психологія управління",
        "educational_program_name": "",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495247",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "081",
        "speciality_name": "Право",
        "educational_program_name": "Право",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010065",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія",
        "educational_program_name": "Біохімія та фізіологія",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія",
        "educational_program_name": "Системна біологія та гідробіоресурси",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Екологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007577",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Промислова екологія та охорона екосистем",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495218",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Хімія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010066",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "103",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Науки про Землю",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04002069",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "104",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Фізика та астрономія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010067",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "106",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Географія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 155",
        "accreditation_end": "28.01.2025",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика та статистика",
        "educational_program_name": "Математика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010068",
        "accreditation_end": "01.07.2025",
    },
    {
        "speciality_code": "112",
        "speciality_name": "Статистика",
        "educational_program_name": "Статистика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007578",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Інформатика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010070",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Комп'ютерна механіка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010071",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Комп'ютерне моделювання та обчислювальні методи",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010069",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "121",
        "speciality_name": "Інженерія програмного забезпечення",
        "educational_program_name": "Інженерія програмного забезпечення",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007579",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "122",
        "speciality_name": "Комп'ютерні науки",
        "educational_program_name": "Комп'ютерні науки",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003211",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "123",
        "speciality_name": "Комп’ютерна інженерія",
        "educational_program_name": "Комп’ютерна інженерія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003212",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "124",
        "speciality_name": "Системний аналіз",
        "educational_program_name": "Системний аналіз",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010072",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "126",
        "speciality_name": "Інформаційні системи та технології",
        "educational_program_name": "Інформаційні системи та технології",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "educational_program_name": "Прикладна механіка",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495229",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "132",
        "speciality_name": "Матеріалознавство",
        "educational_program_name": "Матеріалознавство",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010073",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "133",
        "speciality_name": "Галузеве машинобудування",
        "educational_program_name": "Галузеве машинобудування",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495231",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Ракетні двигуни та енергетичні установки",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010075",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Технології виробництва літальних апаратів",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495232",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "141",
        "speciality_name": "Електроенергетика, електротехніка та електромеханіка",
        "educational_program_name": "Нетрадиційні та відновлювані джерела енергії",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495233",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "144",
        "speciality_name": "Теплоенергетика",
        "educational_program_name": "Теплоенергетика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010076",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "161",
        "speciality_name": "Хімічні технології та інженерія",
        "educational_program_name": "Хімічні технології та інженерія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003213",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "162",
        "speciality_name": "Біотехнології та біоінженерія",
        "educational_program_name": "Біотехнології та біоінженерія",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "172",
        "speciality_name": "Електронні комунікації та радіотехніка",
        "educational_program_name": "Телекомунікації та радіотехніка",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "173",
        "speciality_name": "Авіоніка",
        "educational_program_name": "Авіоніка",
        "accreditation_description": "",
        "accrediation_end": "",
    },
    {
        "speciality_code": "174",
        "speciality_name": "Автоматизація, комп’ютерно-інтегровані технології та робототехніка",
        "educational_program_name": "Автоматизація та комп`ютерно-інтегровані технології",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04017904",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "176",
        "speciality_name": "Мікро- та наносистемна техніка",
        "educational_program_name": "Мікро- та наносистемна техніка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04017905",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "181",
        "speciality_name": "Харчові технології",
        "educational_program_name": "Харчові технології",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1038",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "223",
        "speciality_name": "Медсестринство",
        "educational_program_name": "Медсестринство",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2978",
        "accrediation_end": "01.07.2027",
    },
    {
        "speciality_code": "224",
        "speciality_name": "Технології медичної діагностики та лікування",
        "educational_program_name": "Технології медичної діагностики та лікування",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007581",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "231",
        "speciality_name": "Соціальна робота",
        "educational_program_name": "Соціальна робота",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007582",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "241",
        "speciality_name": "Готельно-ресторанна справа",
        "educational_program_name": "Міжнародний туристичний бізнес",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 7433",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "281",
        "speciality_name": "Публічне управління та адміністрування",
        "educational_program_name": "Публічне управління та адміністрування",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 963",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "291",
        "speciality_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "educational_program_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007583",
        "accrediation_end": "01.07.2025",
    },
    {
        "speciality_code": "241",
        "speciality_name": "Готельно-ресторанна справа",
        "educational_program_name": "Готельно-ресторанна справа",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1038",
        "accrediation_end": "01.07.2026",
    },
    {
        "speciality_code": "292",
        "speciality_name": "Міжнародні економічні відносини",
        "educational_program_name": "Міжнародна економіка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010078",
        "accrediation_end": "01.07.2025",
    },
]

json_phd_accreditation = [
    {
        "speciality_code": "016",
        "speciality_name": "Спеціальна освіта",
        "educational_program_name": "",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "educational_program_name": "Історія та археологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4830",
        "accrediation_end": "20.06.2024",
    },
    {
        "speciality_code": "033",
        "speciality_name": "Філософія",
        "educational_program_name": "Філософія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2388",
        "accrediation_end": "01.07.2027",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "educational_program_name": "Філологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4831",
        "accrediation_end": "20.06.2024",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "educational_program_name": "Економіка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4810",
        "accrediation_end": "20.06.2024",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "educational_program_name": "Політологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2372",
        "accrediation_end": "01.07.2027",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Психологія",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "054",
        "speciality_name": "Соціологія",
        "educational_program_name": "Соціологія",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "educational_program_name": "Журналістика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4807",
        "accrediation_end": "20.06.2024",
    },
    {
        "speciality_code": "072",
        "speciality_name": "Фінанси, банківська справа, страхування та фондовий ринок",
        "educational_program_name": "Фінанси, банківська справа, страхування та фондовий ринок",
        "accreditation_description": "",
        "accrediation_end": "неакредитовано",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "educational_program_name": "Менеджмент",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "076",
        "speciality_name": "Підприємництво та торгівля",
        "educational_program_name": "Підприємництво та торгівля",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "081",
        "speciality_name": "Право",
        "educational_program_name": "Право",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "educational_program_name": "Біологія",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Екологія",
        "educational_program_name": "Екологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2167",
        "accreditation_end": "01.07.2027",
        "status": "акредитовано",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Хімія",
        "educational_program_name": "Хімія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 3021",
        "accreditation_end": "01.07.2027",
        "status": "акредитовано",
    },
    {
        "speciality_code": "104",
        "speciality_name": "Фізика та астрономія",
        "educational_program_name": "Фізика та астрономія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 5910",
        "accreditation_end": "26.09.2024",
        "status": "акредитовано",
    },
    {
        "speciality_code": "105",
        "speciality_name": "Прикладна фізика та наноматеріали",
        "educational_program_name": "Прикладна фізика та наноматеріали",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 6115",
        "accreditation_end": "21.11.2024",
        "status": "акредитовано",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика",
        "educational_program_name": "Математика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 7518",
        "accreditation_end": "16.04.2025",
        "status": "акредитовано",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Прикладна математика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2068",
        "accreditation_end": "01.07.2027",
        "status": "акредитовано",
    },
    {
        "speciality_code": "121",
        "speciality_name": "Інженерія програмного забезпечення",
        "educational_program_name": "Інженерія програмного забезпечення",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "122",
        "speciality_name": "Комп’ютерні науки",
        "educational_program_name": "Комп’ютерні науки",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "123",
        "speciality_name": "Комп’ютерна інженерія",
        "educational_program_name": "Комп’ютерна інженерія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 5906",
        "accreditation_end": "26.09.2024",
        "status": "акредитовано",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "educational_program_name": "Прикладна механіка",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "132",
        "speciality_name": "Матеріалознавство",
        "educational_program_name": "Матеріалознавство",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4882",
        "accreditation_end": "20.06.2024",
        "status": "акредитовано",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Авіаційна та ракетно-космічна техніка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 5903",
        "accreditation_end": "26.09.2024",
        "status": "акредитовано",
    },
    {
        "speciality_code": "172",
        "speciality_name": "Електронні комунікації та радіотехніка",
        "educational_program_name": "Електронні комунікації та радіотехніка",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "173",
        "speciality_name": "Авіоніка",
        "educational_program_name": "Авіоніка",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "174",
        "speciality_name": "Автоматизація, комп’ютерно-інтегровані технології та робототехніка",
        "educational_program_name": "Автоматизація, комп’ютерно-інтегровані технології",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "176",
        "speciality_name": "Мікро- та наносистемна техніка",
        "educational_program_name": "Мікро- та наносистемна техніка",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "224",
        "speciality_name": "Технології медичної діагностики та лікування",
        "educational_program_name": "Технології медичної діагностики та лікування",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
    {
        "speciality_code": "291",
        "speciality_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "educational_program_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accreditation_end": "30.05.2024",
        "status": "акредитовано",
    },
    {
        "speciality_code": "292",
        "speciality_name": "Міжнародні економічні відносини",
        "educational_program_name": "Міжнародні економічні відносини",
        "accreditation_description": "",
        "accreditation_end": "",
        "status": "неакредитовано",
    },
]
