json_accreditation = [
    {
        "speciality_code": "016",
        "speciality_name": "Спеціальна освіта",
        "educational_program_name": "Спеціальна освіта",
        "level": "phd",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "educational_program_name": "Історія та археологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4830",
        "accrediation_end": "20.06.2024",
        "level": "phd",
    },
    {
        "speciality_code": "033",
        "speciality_name": "Філософія",
        "educational_program_name": "Філософія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2388",
        "accrediation_end": "01.07.2027",
        "level": "phd",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "educational_program_name": "Філологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4831",
        "accrediation_end": "20.06.2024",
        "level": "phd",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "educational_program_name": "Економіка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4810",
        "accrediation_end": "20.06.2024",
        "level": "phd",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "educational_program_name": "Політологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2372",
        "accrediation_end": "01.07.2027",
        "level": "phd",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Психологія",
        "level": "phd",
    },
    {
        "speciality_code": "054",
        "speciality_name": "Соціологія",
        "educational_program_name": "Соціологія",
        "level": "phd",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "educational_program_name": "Журналістика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4807",
        "accrediation_end": "20.06.2024",
        "level": "phd",
    },
    {
        "speciality_code": "072",
        "speciality_name": "Фінанси, банківська справа, страхування та фондовий ринок",
        "educational_program_name": "Фінанси, банківська справа, страхування та фондовий ринок",
        "level": "phd",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "educational_program_name": "Менеджмент",
        "level": "phd",
    },
    {
        "speciality_code": "076",
        "speciality_name": "Підприємництво та торгівля",
        "educational_program_name": "Підприємництво та торгівля",
        "level": "phd",
    },
    {
        "speciality_code": "081",
        "speciality_name": "Право",
        "educational_program_name": "Право",
        "level": "phd",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "educational_program_name": "Біологія",
        "level": "phd",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Екологія",
        "educational_program_name": "Екологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2167",
        "accreditation_end": "01.07.2027",
        "level": "phd",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Хімія",
        "educational_program_name": "Хімія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 3021",
        "accreditation_end": "01.07.2027",
        "level": "phd",
    },
    {
        "speciality_code": "104",
        "speciality_name": "Фізика та астрономія",
        "educational_program_name": "Фізика та астрономія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 5910",
        "accreditation_end": "26.09.2024",
        "level": "phd",
    },
    {
        "speciality_code": "105",
        "speciality_name": "Прикладна фізика та наноматеріали",
        "educational_program_name": "Прикладна фізика та наноматеріали",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 6115",
        "accreditation_end": "21.11.2024",
        "level": "phd",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика",
        "educational_program_name": "Математика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 7518",
        "accreditation_end": "16.04.2025",
        "level": "phd",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Прикладна математика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2068",
        "accreditation_end": "01.07.2027",
        "level": "phd",
    },
    {
        "speciality_code": "121",
        "speciality_name": "Інженерія програмного забезпечення",
        "educational_program_name": "Інженерія програмного забезпечення",
        "level": "phd",
    },
    {
        "speciality_code": "122",
        "speciality_name": "Комп'ютерні науки",
        "educational_program_name": "Комп'ютерні науки",
        "level": "phd",
    },
    {
        "speciality_code": "123",
        "speciality_name": "Комп'ютерна інженерія",
        "educational_program_name": "Комп'ютерна інженерія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 5906",
        "accreditation_end": "26.09.2024",
        "level": "phd",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "educational_program_name": "Прикладна механіка",
        "level": "phd",
    },
    {
        "speciality_code": "132",
        "speciality_name": "Матеріалознавство",
        "educational_program_name": "Матеріалознавство",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 4882",
        "accreditation_end": "20.06.2024",
        "level": "phd",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Авіаційна та ракетно-космічна техніка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 5903",
        "accreditation_end": "26.09.2024",
        "level": "phd",
    },
    {
        "speciality_code": "172",
        "speciality_name": "Електронні комунікації та радіотехніка",
        "educational_program_name": "Електронні комунікації та радіотехніка",
        "level": "phd",
    },
    {
        "speciality_code": "173",
        "speciality_name": "Авіоніка",
        "educational_program_name": "Авіоніка",
        "level": "phd",
    },
    {
        "speciality_code": "174",
        "speciality_name": "Автоматизація, комп'ютерно-інтегровані технології та робототехніка",
        "educational_program_name": "Автоматизація, комп'ютерно-інтегровані технології",
        "level": "phd",
    },
    {
        "speciality_code": "176",
        "speciality_name": "Мікро- та наносистемна техніка",
        "educational_program_name": "Мікро- та наносистемна техніка",
        "level": "phd",
    },
    {
        "speciality_code": "224",
        "speciality_name": "Технології медичної діагностики та лікування",
        "educational_program_name": "Технології медичної діагностики та лікування",
        "level": "phd",
    },
    {
        "speciality_code": "291",
        "speciality_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "educational_program_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accreditation_end": "30.05.2024",
        "level": "phd",
    },
    {
        "speciality_code": "292",
        "speciality_name": "Міжнародні економічні відносини",
        "educational_program_name": "Міжнародні економічні відносини",
        "level": "phd",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "educational_program_name": "Середня освіта (Біологія та здоров'я людини)",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1187",
        "accrediation_end": "01.07.2026",
        "level": "master",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "educational_program_name": "Середня освіта (Географія)",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1140",
        "accrediation_end": "01.07.2026",
        "level": "master",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "educational_program_name": "Середня освіта (Історія)",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 3966",
        "accrediation_end": "01.07.2028",
        "level": "master",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "educational_program_name": "Середня освіта (Математика)",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 124",
        "accrediation_end": "28.01.2025",
        "level": "master",
    },
    {
        "speciality_code": "016",
        "speciality_name": "Спеціальна освіта",
        "educational_program_name": "Логопедія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495201",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "022",
        "speciality_name": "Дизайн",
        "educational_program_name": "Дизайн візуального середовища",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 129",
        "accrediation_end": "28.01.2025",
        "level": "master",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "educational_program_name": "Історія та археологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010057",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "033",
        "speciality_name": "Філософія",
        "educational_program_name": "Філософія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003209",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "029",
        "speciality_name": "Інформаційна, бібліотечна та архівна справа",
        "educational_program_name": "Менеджмент інформаційної діяльності",
        "level": "master",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Германські мови та літератури (переклад включно), перша - англійська",
        "educational_program_name": "Англійська та друга західноєвропейська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Германські мови та літератури (переклад включно), перша - англійська",
        "educational_program_name": "Переклад з англійської та німецької мов",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Германські мови та літератури (переклад включно), перша - німецька",
        "educational_program_name": "Німецька та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Романські мови та літератури (переклад включно), перша - французька",
        "educational_program_name": "Французька та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Східні мови та літератури (переклад включно), перша - китайська",
        "educational_program_name": "Китайська та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Східні мови та літератури (переклад включно), перша - японська",
        "educational_program_name": "Японська та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Українська мова та література",
        "educational_program_name": "Українська мова та література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495246",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "educational_program_name": "Бізнес-аналітика та інформаційна безпека",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010058",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "educational_program_name": "Політологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010059",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Кризова та реабілітаційна психологія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495247",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Психологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010060",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Психологія управління",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495247",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "054",
        "speciality_name": "Соціологія",
        "educational_program_name": "Соціологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003210",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "educational_program_name": "Медіакомунікації",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010061",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "educational_program_name": "Реклама і зв`язки з громадськістю",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010063",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "071",
        "speciality_name": "Облік і оподаткування",
        "educational_program_name": "Облік і оподаткування",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007573",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "educational_program_name": "Бізнес-адміністрування",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495213",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "educational_program_name": "Міжнародний менеджмент",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495213",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "075",
        "speciality_name": "Маркетинг",
        "educational_program_name": "Маркетинг",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007575",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "076",
        "speciality_name": "Підприємництво та торгівля",
        "educational_program_name": "Економіка підприємства та управління бізнесом",
        "level": "master",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Психологія управління",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495247",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "081",
        "speciality_name": "Право",
        "educational_program_name": "Право",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010065",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія",
        "educational_program_name": "Біохімія та фізіологія",
        "level": "master",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія",
        "educational_program_name": "Системна біологія та гідробіоресурси",
        "level": "master",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Екологія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007577",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Промислова екологія та охорона екосистем",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495218",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Хімія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010066",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "103",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Науки про Землю",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04002069",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "104",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Фізика та астрономія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010067",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "106",
        "speciality_name": "Природничі науки",
        "educational_program_name": "Географія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 155",
        "accreditation_end": "28.01.2025",
        "level": "master",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика та статистика",
        "educational_program_name": "Математика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010068",
        "accreditation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "112",
        "speciality_name": "Статистика",
        "educational_program_name": "Статистика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007578",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Інформатика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010070",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Комп'ютерна механіка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010071",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Комп'ютерне моделювання та обчислювальні методи",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010069",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "121",
        "speciality_name": "Інженерія програмного забезпечення",
        "educational_program_name": "Інженерія програмного забезпечення",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007579",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "122",
        "speciality_name": "Комп'ютерні науки",
        "educational_program_name": "Комп'ютерні науки",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003211",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "123",
        "speciality_name": "Комп'ютерна інженерія",
        "educational_program_name": "Комп'ютерна інженерія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003212",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "124",
        "speciality_name": "Системний аналіз",
        "educational_program_name": "Системний аналіз",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010072",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "126",
        "speciality_name": "Інформаційні системи та технології",
        "educational_program_name": "Інформаційні системи та технології",
        "level": "master",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "educational_program_name": "Прикладна механіка",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495229",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "132",
        "speciality_name": "Матеріалознавство",
        "educational_program_name": "Матеріалознавство",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010073",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "133",
        "speciality_name": "Галузеве машинобудування",
        "educational_program_name": "Галузеве машинобудування",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495231",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Ракетні двигуни та енергетичні установки",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010075",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Технології виробництва літальних апаратів",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495232",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "141",
        "speciality_name": "Електроенергетика, електротехніка та електромеханіка",
        "educational_program_name": "Нетрадиційні та відновлювані джерела енергії",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495233",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "144",
        "speciality_name": "Теплоенергетика",
        "educational_program_name": "Теплоенергетика",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010076",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "161",
        "speciality_name": "Хімічні технології та інженерія",
        "educational_program_name": "Хімічні технології та інженерія",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04003213",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "162",
        "speciality_name": "Біотехнології та біоінженерія",
        "educational_program_name": "Біотехнології та біоінженерія",
        "level": "master",
    },
    {
        "speciality_code": "172",
        "speciality_name": "Електронні комунікації та радіотехніка",
        "educational_program_name": "Телекомунікації та радіотехніка",
        "level": "master",
    },
    {
        "speciality_code": "173",
        "speciality_name": "Авіоніка",
        "educational_program_name": "Авіоніка",
        "level": "master",
    },
    {
        "speciality_code": "174",
        "speciality_name": "Автоматизація, комп'ютерно-інтегровані технології та робототехніка",
        "educational_program_name": "Автоматизація та комп`ютерно-інтегровані технології",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04017904",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "176",
        "speciality_name": "Мікро- та наносистемна техніка",
        "educational_program_name": "Мікро- та наносистемна техніка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04017905",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "181",
        "speciality_name": "Харчові технології",
        "educational_program_name": "Харчові технології",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1038",
        "accrediation_end": "01.07.2026",
        "level": "master",
    },
    {
        "speciality_code": "223",
        "speciality_name": "Медсестринство",
        "educational_program_name": "Медсестринство",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 2978",
        "accrediation_end": "01.07.2027",
        "level": "master",
    },
    {
        "speciality_code": "224",
        "speciality_name": "Технології медичної діагностики та лікування",
        "educational_program_name": "Технології медичної діагностики та лікування",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007581",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "231",
        "speciality_name": "Соціальна робота",
        "educational_program_name": "Соціальна робота",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007582",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "241",
        "speciality_name": "Готельно-ресторанна справа",
        "educational_program_name": "Міжнародний туристичний бізнес",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 7433",
        "accrediation_end": "01.07.2026",
        "level": "master",
    },
    {
        "speciality_code": "281",
        "speciality_name": "Публічне управління та адміністрування",
        "educational_program_name": "Публічне управління та адміністрування",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 963",
        "accrediation_end": "01.07.2026",
        "level": "master",
    },
    {
        "speciality_code": "291",
        "speciality_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "educational_program_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04007583",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "241",
        "speciality_name": "Готельно-ресторанна справа",
        "educational_program_name": "Готельно-ресторанна справа",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1038",
        "accrediation_end": "01.07.2026",
        "level": "master",
    },
    {
        "speciality_code": "292",
        "speciality_name": "Міжнародні економічні відносини",
        "educational_program_name": "Міжнародна економіка",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми УД04010078",
        "accrediation_end": "01.07.2025",
        "level": "master",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Англійська мова та зарубіжна література",
        "educational_program_name": "Середня освіта: Англійська мова і література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495138",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Біологія та здоров'я людини",
        "educational_program_name": "Середня освіта (Біологія та здоров'я людини)",
        "accreditation_description": "Сертифікат про акредитацію спеціальності УД 04009183",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Географія",
        "educational_program_name": "Середня освіта (Географія)",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495143",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Історія",
        "educational_program_name": "Середня освіта (Історія)",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495139",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Математика",
        "educational_program_name": "Середня освіта (Математика)",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495140",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Українська мова і література",
        "educational_program_name": "Середня освіта: Українська мова і література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495137",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Фізика та астрономія",
        "educational_program_name": "Середня освіта (Фізика)",
        "level": "bachelor",
    },
    {
        "speciality_code": "014",
        "speciality_name": "Середня освіта",
        "speciality_specialization": "Хімія",
        "educational_program_name": "Середня освіта (Хімія)",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495142",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "016",
        "speciality_name": "Спеціальна освіта",
        "speciality_specialization": "Логопедія",
        "educational_program_name": "Спеціальна освіта: логопедія та олігофренопедагогіка",
        "level": "bachelor",
    },
    {
        "speciality_code": "022",
        "speciality_name": "Дизайн",
        "speciality_specialization": "Графічний дизайн",
        "educational_program_name": "Дизайн",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495145",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "023",
        "speciality_name": "Образотворче мистецтво, декоративне мистецтво, реставрація",
        "educational_program_name": "Образотворче та декоративне мистецтво",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495146",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "029",
        "speciality_name": "Інформаційна, бібліотечна та архівна справа",
        "educational_program_name": "Диджитальні медіа",
        "level": "bachelor",
    },
    {
        "speciality_code": "031",
        "speciality_name": "Релігієзнавство",
        "educational_program_name": "Релігієзнавство",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495147",
        "accrediation_end": "01.07.2027",
        "level": "bachelor",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "educational_program_name": "Європейські студії та американістика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495148",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "educational_program_name": "Історія та археологія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495148",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "032",
        "speciality_name": "Історія та археологія",
        "educational_program_name": "Історична україністика та прикладна історія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495148",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "033",
        "speciality_name": "Філософія",
        "educational_program_name": "Філософія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495149",
        "accrediation_end": "01.07.2027",
        "level": "bachelor",
    },
    {
        "speciality_code": "034",
        "speciality_name": "Культурологія",
        "educational_program_name": "Культурологія: менеджмент культурних процесів",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Германські мови та літератури (переклад включно), перша - англійська",
        "educational_program_name": "Англійська та друга західноєвропейська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Германські мови та літератури (переклад включно), перша - англійська",
        "educational_program_name": "Переклад з англійської та німецької мов",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Германські мови та літератури (переклад включно), перша - німецька",
        "educational_program_name": "Німецька та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Прикладна лінгвістика",
        "educational_program_name": "Прикладна лінгвістика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Романські мови та літератури (переклад включно), перша - французька",
        "educational_program_name": "Французька та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Слов'янські мови та літератури (переклад включно), перша - польська",
        "educational_program_name": "Польська мова та література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Східні мови та літератури (переклад включно), перша - китайська",
        "educational_program_name": "Китайська та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Східні мови та літератури (переклад включно), перша - японська",
        "educational_program_name": "Японська та англійська мови і літератури",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "035",
        "speciality_name": "Філологія",
        "speciality_specialization": "Українська мова та література",
        "educational_program_name": "Українська мова та література",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495150",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "educational_program_name": "Бізнес-аналітика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495151",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "051",
        "speciality_name": "Економіка",
        "educational_program_name": "Цифрова й інформаційна економіка",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495151",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "educational_program_name": "Політична соціологія та політичний менеджмент",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495152",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "052",
        "speciality_name": "Політологія",
        "educational_program_name": "Політологія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495152",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Практична психологія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495153",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "053",
        "speciality_name": "Психологія",
        "educational_program_name": "Психологія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495153",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "054",
        "speciality_name": "Соціологія",
        "educational_program_name": "Соціологія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495154",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "educational_program_name": "Журналістика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495157",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "061",
        "speciality_name": "Журналістика",
        "educational_program_name": "Реклама і зв'язки з громадськістю",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495157",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "071",
        "speciality_name": "Облік і оподаткування",
        "educational_program_name": "Бізнес-консалтинг",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495158",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "073",
        "speciality_name": "Менеджмент",
        "educational_program_name": "Міжнародний менеджмент",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495160",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "075",
        "speciality_name": "Маркетинг",
        "educational_program_name": "Маркетинг",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1720",
        "accrediation_end": "01.07.2026",
        "level": "bachelor",
    },
    {
        "speciality_code": "076",
        "speciality_name": "Підприємництво та торгівля",
        "educational_program_name": "Економіка підприємства та організація бізнесу",
        "level": "bachelor",
    },
    {
        "speciality_code": "081",
        "speciality_name": "Право",
        "educational_program_name": "Право",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495163",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "educational_program_name": "Біоінформатика",
        "level": "bachelor",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "educational_program_name": "Біорізноманіття та ландшафтний дизайн",
        "level": "bachelor",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "educational_program_name": "Біохімія та фізіологія",
        "level": "bachelor",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "educational_program_name": "Мікробіологія та вірусологія",
        "level": "bachelor",
    },
    {
        "speciality_code": "091",
        "speciality_name": "Біологія та біохімія",
        "educational_program_name": "Системна біологія та гідробіоресурси",
        "level": "bachelor",
    },
    {
        "speciality_code": "101",
        "speciality_name": "Екологія",
        "educational_program_name": "Екологія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495165",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Хімія",
        "educational_program_name": "Хімічний аналіз та експертиза матеріалів та виробів",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495166",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "102",
        "speciality_name": "Хімія",
        "educational_program_name": "Хімія лікарських речовин",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495166",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "103",
        "speciality_name": "Науки про Землю",
        "educational_program_name": "Геоекологічний інжиніринг",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495167",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "104",
        "speciality_name": "Фізика та астрономія",
        "educational_program_name": "Фізика та астрономія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495168",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "105",
        "speciality_name": "Прикладна фізика та наноматеріали",
        "educational_program_name": "Радіофізика, електроніка та оптоінформатика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495169",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "106",
        "speciality_name": "Географія",
        "educational_program_name": "Географія рекреації та туризму",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accrediation_end": "30.05.2024",
        "level": "bachelor",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика",
        "educational_program_name": "Математика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495170",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "111",
        "speciality_name": "Математика",
        "educational_program_name": "Математика інтелектуальних систем",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495170",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "112",
        "speciality_name": "Статистика",
        "educational_program_name": "Статистика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495171",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Комп'ютерне моделювання та технології програмування",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Комп'ютерний інжиніринг безпілотних літальних апаратів і комплексів",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Облік, аналітика та моделювання бізнес-систем",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "113",
        "speciality_name": "Прикладна математика",
        "educational_program_name": "Прикладне комп'ютерне та математичне моделювання",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495172",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "121",
        "speciality_name": "Інженерія програмного забезпечення",
        "educational_program_name": "Інженерія програмного забезпечення",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495173",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "122",
        "speciality_name": "Комп'ютерні науки",
        "educational_program_name": "Комп'ютерні науки",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495244",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "123",
        "speciality_name": "Комп'ютерна інженерія",
        "educational_program_name": "Комп'ютерна інженерія",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495175",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "124",
        "speciality_name": "Системний аналіз",
        "educational_program_name": "Системний аналіз",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495176",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "125",
        "speciality_name": "Кібербезпека та захист інформації",
        "educational_program_name": "Кібербезпека та системи технічного захисту",
        "accrediation_end": "неакредитовано",
        "level": "bachelor",
    },
    {
        "speciality_code": "126",
        "speciality_name": "Інформаційні системи та технології",
        "educational_program_name": "Інформаційні системи та технології",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accrediation_end": "30.05.2024",
        "level": "bachelor",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "educational_program_name": "Інжиніринг механотронних і робототехнічних систем",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495178",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "131",
        "speciality_name": "Прикладна механіка",
        "educational_program_name": "Комп'ютерні технології інженерії міцності",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495178",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "132",
        "speciality_name": "Матеріалознавство",
        "educational_program_name": "Матеріалознавство",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495179",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "133",
        "speciality_name": "Галузеве машинобудування",
        "educational_program_name": "Галузеве машинобудування",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495180",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "133",
        "speciality_name": "Галузеве машинобудування",
        "educational_program_name": "Комп'ютерний інжиніринг і технології автоматизованих виробництв",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495180",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Авіаційна та ракетно-космічна техніка",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495181",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Проєктування, виробництво та експлуатація безпілотних систем і комплексів",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495181",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "134",
        "speciality_name": "Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Ракетні двигуни",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495181",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "141",
        "speciality_name": "Електроенергетика, електротехніка та електромеханіка",
        "educational_program_name": "Відновлювані джерела енергії та енергоефективні технології",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495182",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "144",
        "speciality_name": "Теплоенергетика",
        "educational_program_name": "Теплоенергетика",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495183",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "161",
        "speciality_name": "Хімічні технології та інженерія",
        "educational_program_name": "Хімічні технології та інженерія",
        "accrediation_end": "неакредитовано",
        "level": "bachelor",
    },
    {
        "speciality_code": "162",
        "speciality_name": "Біотехнології та біоінженерія",
        "educational_program_name": "Біотехнології та біоінженерія",
        "accrediation_end": "неакредитовано",
        "level": "bachelor",
    },
    {
        "speciality_code": "172",
        "speciality_name": "Електронні комунікації та радіотехніка",
        "educational_program_name": "Інфокомунікації та системи зв'язку",
        "accrediation_end": "неакредитовано",
        "level": "bachelor",
    },
    {
        "speciality_code": "174",
        "speciality_name": "Автоматизація, комп'ютерно-інтегровані технології та робототехніка",
        "educational_program_name": "Автоматизація та комп`ютерно-інтегровані технології",
        "accrediation_end": "неакредитовано",
        "level": "bachelor",
    },
    {
        "speciality_code": "181",
        "speciality_name": "Харчові технології",
        "educational_program_name": "Ресторанні та крафтові технології здорового харчування",
        "accrediation_end": "неакредитовано",
        "level": "bachelor",
    },
    {
        "speciality_code": "183",
        "speciality_name": "Технології захисту навколишнього середовища",
        "educational_program_name": "Екоаналітика та техногенна безпека",
        "accrediation_end": "неакредитовано",
        "level": "bachelor",
    },
    {
        "speciality_code": "223",
        "speciality_name": "Медсестринство",
        "educational_program_name": "Медсестринство",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1719",
        "accrediation_end": "01.07.2026",
        "level": "bachelor",
    },
    {
        "speciality_code": "224",
        "speciality_name": "Технології медичної діагностики та лікування",
        "educational_program_name": "Технології медичної діагностики та лікування",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495191",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "176",
        "speciality_name": "Мікро- та наносистемна техніка",
        "educational_program_name": "Мікро- та наносистемна техніка",
        "accreditation_description": "Сертифікат про акредитацію спеціальності УД 04017903",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "181",
        "speciality_name": "Харчові технології",
        "educational_program_name": "Харчові технології",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 1712",
        "accrediation_end": "01.07.2026",
        "level": "bachelor",
    },
    {
        "speciality_code": "227",
        "speciality_name": "Терапія та реабілітація",
        "educational_program_name": "Фізична терапія, ерготерапія",
        "level": "bachelor",
    },
    {
        "speciality_code": "229",
        "speciality_name": "Громадське здоров`я",
        "level": "bachelor",
    },
    {
        "speciality_code": "231",
        "speciality_name": "Соціальна робота",
        "speciality_specialization": "Соціальна робота",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495192",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
    {
        "speciality_code": "241",
        "speciality_name": "Готельно-ресторанна справа",
        "speciality_specialization": "Готельно-ресторанна справа",
        "level": "bachelor",
    },
    {
        "speciality_code": "242",
        "speciality_name": "Туризм і рекреація",
        "educational_program_name": "Міжнародний туризм",
        "level": "bachelor",
    },
    {
        "speciality_code": "281",
        "speciality_name": "Публічне управління та адміністрування",
        "educational_program_name": "Публічне управління, медіація, електронне врядування",
        "level": "bachelor",
    },
    {
        "speciality_code": "291",
        "speciality_name": "Міжнародні відносини",
        "speciality_specialization": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "educational_program_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "accreditation_description": "Сертифікат про акредитацію освітньої програми 0",
        "accrediation_end": "30.05.2024",
        "level": "bachelor",
    },
    {
        "speciality_code": "292",
        "speciality_name": "Міжнародні відносини",
        "speciality_specialization": "Міжнародна економіка",
        "educational_program_name": "Міжнародні економічні відносини",
        "accreditation_description": "Сертифікат про акредитацію спеціальності НД 0495243",
        "accrediation_end": "01.07.2025",
        "level": "bachelor",
    },
]

offers = [
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта/ 014.05 Середня освіта (Біологія та здоров’я людини)",
        "educational_program_name": "Середня освіта (Біологія та здоров’я людини)",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "091 Біологія та біохімія",
        "educational_program_name": "Біохімія та фізіологія",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "091 Біологія та біохімія",
        "educational_program_name": "Мікробіологія та вірусологія",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "091 Біологія та біохімія",
        "educational_program_name": "Біорізноманіття та ландшафтний дизайн",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "091 Біологія та біохімія",
        "educational_program_name": "Системна біологія та гідробіоресурси",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "091 Біологія та біохімія",
        "educational_program_name": "Біоінформатика",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "101 Екологія",
        "educational_program_name": "Екологія",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "162 Біотехнології та біоінженерія",
        "educational_program_name": "Біотехнології та біоінженерія",
        "faculty": "Біолого - екологічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта/014.06 Середня освіта (Хімія)",
        "educational_program_name": "Середня освіта (Хімія)",
        "faculty": "Хімічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "102 Хімія",
        "educational_program_name": "Хімічний аналіз та експертиза матеріалів і виробів",
        "faculty": "Хімічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "102 Хімія",
        "educational_program_name": "Хімія лікарських речовин",
        "faculty": "Хімічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "161 Хімічні технології та інженерія",
        "educational_program_name": "Хімічні технології та інженерія",
        "faculty": "Хімічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "181 Харчові технології",
        "educational_program_name": "Ресторанні та крафтові технології здорового харчування",
        "faculty": "Хімічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "181 Харчові технології",
        "educational_program_name": "Харчові технології",
        "faculty": "Хімічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта/014.03 Середня освіта (Історія)",
        "educational_program_name": "Середня освіта (Історія)",
        "faculty": "Історичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта/014.07 Середня освіта (Географія)",
        "educational_program_name": "Середня освіта (Географія)",
        "faculty": "Історичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "032 Історія та археологія",
        "educational_program_name": "Історична україністика та прикладна історія",
        "faculty": "Історичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "032 Історія та археологія",
        "educational_program_name": "Історія та археологія",
        "faculty": "Історичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "032 Історія та археологія",
        "educational_program_name": "Європейські студії та американістика",
        "faculty": "Історичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "106 Географія",
        "educational_program_name": "Географія рекреації та туризму",
        "faculty": "Історичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "103 Науки про Землю",
        "educational_program_name": "Геоекологічний інжиніринг",
        "faculty": "Історичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта/014.01 Середня освіта (Українська мова і література)",
        "educational_program_name": "Середня освіта: Українська мова і література",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "фіксована",
        "speciality": "022 Дизайн (022.01 Графічний дизайн)",
        "educational_program_name": "Дизайн",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "фіксована",
        "speciality": "023 Образотворче мистецтво, декоративне мистецтво, реставрація",
        "educational_program_name": "Образотворче та декоративне мистецтво",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.01 Українська мова та література)",
        "educational_program_name": "Українська мова та література",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.033 Слов’янські мови та літератури (переклад включно), перша - польська)",
        "educational_program_name": "Польська мова та література",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.041 Германські мови та літератури (переклад включно), перша - англійська)",
        "educational_program_name": "Англійська та друга західноєвропейська мови і літератури",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.041 Германські мови та літератури (переклад включно), перша - англійська)",
        "educational_program_name": "Переклад з англійської та німецької мов",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.043 Германські мови та літератури (переклад включно), перша - німецька)",
        "educational_program_name": "Німецька та англійська мови і літератури",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.055 Романські мови та літератури (переклад включно), перша - французька)",
        "educational_program_name": "Французька та англійська мови і літератури",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.065 Східні мови та літератури (переклад включно), перша - китайська)",
        "educational_program_name": "Китайська та англійська мови і літератури",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.069 Східні мови та літератури (переклад включно), перша - японська)",
        "educational_program_name": "Японська та англійська мови і літератури",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.10 Прикладна лінгвістика)",
        "educational_program_name": "Прикладна лінгвістика",
        "faculty": "Факультет української й іноземної мови та мистецтвознавства",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "016 Спеціальна освіта (016.01 Спеціальна освіта (Логопедія))",
        "educational_program_name": "Спеціальна освіта: олігофренопедагогіка та логопедія",
        "faculty": "Факультет психології та спеціальної освіти",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "053 Психологія",
        "educational_program_name": "Практична психологія",
        "faculty": "Факультет психології та спеціальної освіти",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "053 Психологія",
        "educational_program_name": "Психологія",
        "faculty": "Факультет психології та спеціальної освіти",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "061 Журналістика",
        "educational_program_name": "Журналістика",
        "faculty": "Факультет систем і засобів масової комунікації",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "061 Журналістика",
        "educational_program_name": "Реклама і зв’язки з громадськістю",
        "faculty": "Факультет систем і засобів масової комунікації",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "029 Інформаційна, бібліотечна та архівна справа",
        "educational_program_name": "Диджитальні медіа",
        "faculty": "Факультет систем і засобів масової комунікації",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "033 Філософія",
        "educational_program_name": "Філософія",
        "faculty": "Факультет суспільних наук та міжнародних відносин",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "034 Культурологія",
        "educational_program_name": "Культурологія: менеджмент культурних процесів",
        "faculty": "Факультет суспільних наук та міжнародних відносин",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "052 Політологія",
        "educational_program_name": "Політична соціологія та політичний менеджмент",
        "faculty": "Факультет суспільних наук та міжнародних відносин",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "052 Політологія",
        "educational_program_name": "Політологія",
        "faculty": "Факультет суспільних наук та міжнародних відносин",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "054 Соціологія",
        "educational_program_name": "Соціологія",
        "faculty": "Факультет суспільних наук та міжнародних відносин",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "281 Публічне управління та адміністрування",
        "educational_program_name": "Публічне управління, медіація, електронне врядування",
        "faculty": "Факультет суспільних наук та міжнародних відносин",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "291 Міжнародні відносини, суспільні комунікації та регіональні студії",
        "educational_program_name": "Міжнародні відносини, суспільні комунікації та регіональні студії",
        "faculty": "Факультет суспільних наук та міжнародних відносин",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "051 Економіка",
        "educational_program_name": "Бізнес-аналітика",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "051 Економіка",
        "educational_program_name": "Цифрова й інформаційна економіка",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "071 Облік і оподаткування",
        "educational_program_name": "Бізнес-консалтинг",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "072 Фінанси, банківська справа, страхування та фондовий ринок",
        "educational_program_name": "Фінанси, банківська справа та страхування",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "073 Менеджмент",
        "educational_program_name": "Міжнародний менеджмент",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "075 Маркетинг",
        "educational_program_name": "Маркетинг",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "076 Підприємництво та торгівля",
        "educational_program_name": "Економіка підприємства та організація бізнесу",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "241 Готельно-ресторанна справа",
        "educational_program_name": "Готельно-ресторанна справа",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "242 Туризм і рекреація",
        "educational_program_name": "Міжнародний туризм",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "292 Міжнародні економічні відносини",
        "educational_program_name": "Міжнародна економіка",
        "faculty": "Факультет економіки",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта/014.04 Середня освіта (Математика)",
        "educational_program_name": "Середня освіта (Математика)",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "111 Математика",
        "educational_program_name": "Математика",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "111 Математика",
        "educational_program_name": "Математика інтелектуальних систем",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "112 Статистика",
        "educational_program_name": "Статистика",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "113 Прикладна математика",
        "educational_program_name": "Прикладне комп’ютерне та математичне моделювання",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "113 Прикладна математика",
        "educational_program_name": "Комп’ютерний інжиніринг безпілотних літальних апаратів і комплексів",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "131 Прикладна механіка",
        "educational_program_name": "Комп'ютерні технології інженерії міцності",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "144 Теплоенергетика",
        "educational_program_name": "Теплоенергетика",
        "faculty": "Механіко-математичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "081 Право",
        "educational_program_name": "Право",
        "faculty": "Юридичний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "113 Прикладна математика",
        "educational_program_name": "Комп'ютерне моделювання та технології програмування",
        "faculty": "Факультет прикладної математики",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "121 Інженерія програмного забезпечення",
        "educational_program_name": "Інженерія програмного забезпечення",
        "faculty": "Факультет прикладної математики",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "124 Системний аналіз",
        "educational_program_name": "Системний аналіз",
        "faculty": "Факультет прикладної математики",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "126 Інформаційні системи та технології",
        "educational_program_name": "Інформаційні системи та технології",
        "faculty": "Факультет прикладної математики",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "122 Комп’ютерні науки",
        "educational_program_name": "Комп’ютерні науки",
        "faculty": "Факультет фізики, електроніки та комп’ютерних систем",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "123 Комп’ютерна інженерія",
        "educational_program_name": "Комп’ютерна інженерія",
        "faculty": "Факультет фізики, електроніки та комп’ютерних систем",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "176 Мікро- та наносистемна техніка",
        "educational_program_name": "Мікро- та наносистемна техніка",
        "faculty": "Факультет фізики, електроніки та комп’ютерних систем",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "172 Електронні комунікації та радіотехніка",
        "educational_program_name": "Інфокомунікації та системи зв'язку",
        "faculty": "Факультет фізики, електроніки та комп’ютерних систем",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта/014.08 Середня освіта (Фізика та астрономія)",
        "educational_program_name": "Середня освіта (Фізика)",
        "faculty": "Факультет фізики, електроніки та комп’ютерних систем",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "104 Фізика та астрономія",
        "educational_program_name": "Фізика та астрономія",
        "faculty": "Факультет фізики, електроніки та комп’ютерних систем",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "105 Прикладна фізика та наноматеріали",
        "educational_program_name": "Радіофізика, електроніка та оптоінформатика",
        "faculty": "Факультет фізики, електроніки та комп’ютерних систем",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "125 Кібербезпека та захист інформації",
        "educational_program_name": "Кібербезпека та системи технічного захисту",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "131 Прикладна механіка",
        "educational_program_name": "Інжиніринг механотронних і робототехнічних систем",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "132 Матеріалознавство",
        "educational_program_name": "Матеріалознавство",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "133 Галузеве машинобудування",
        "educational_program_name": "Галузеве машинобудування",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "133 Галузеве машинобудування",
        "educational_program_name": "Комп’ютерний інжиніринг і технології автоматизованих виробництв",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "134 Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Авіаційна та ракетно-космічна техніка",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "134 Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Проектування, виробництво і експлуатація безпілотних систем і комплексів",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "134 Авіаційна та ракетно-космічна техніка",
        "educational_program_name": "Ракетні двигуни",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "141 Електроенергетика, електротехніка та електромеханіка",
        "educational_program_name": "Відновлювані джерела енергії та енергоефективні технології",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "174 Автоматизація, комп’ютерно-інтегровані технології та робототехніка",
        "educational_program_name": "Автоматизація та комп'ютерно-інтегровані технології",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "183 Технології захисту навколишнього середовища",
        "educational_program_name": "Екоаналітика та техногенна безпека",
        "faculty": "Фізико-технічний факультет",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "223 Медсестринство (223.01 Медсестринство)",
        "educational_program_name": "Медсестринство",
        "faculty": "Факультет медичних технологій діагностики та реабілітації",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "224 Технології медичної діагностики та лікування",
        "educational_program_name": "Технології медичної діагностики та лікування",
        "faculty": "Факультет медичних технологій діагностики та реабілітації",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "227 Терапія та реабілітація (227.1 Фізична терапія)",
        "educational_program_name": "Фізична терапія, ерготерапія",
        "faculty": "Факультет медичних технологій діагностики та реабілітації",
    },
    {
        "study_form": "DAY",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "231 Соціальна робота",
        "educational_program_name": "Соціальна робота",
        "faculty": "Факультет медичних технологій діагностики та реабілітації",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "053 Психологія",
        "educational_program_name": "Психологія",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "061 Журналістика",
        "educational_program_name": "Журналістика",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "073 Менеджмент",
        "educational_program_name": "Міжнародний менеджмент",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "076 Підприємництво та торгівля",
        "educational_program_name": "Економіка підприємства та організація бізнесу",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "081 Право",
        "educational_program_name": "Право",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "014 Середня освіта / 014.021 Середня освіта (Мова та зарубіжна література (англійська))",
        "educational_program_name": "Середня освіта: Англійська мова і література",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "014 Середня освіта/014.01 Середня освіта (Українська мова і література)",
        "educational_program_name": "Середня освіта: Українська мова і література",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "016 Спеціальна освіта (016.01 Спеціальна освіта (Логопедія))",
        "educational_program_name": "Спеціальна освіта: олігофренопедагогіка та логопедія",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "небюджетна",
        "speciality": "035 Філологія (035.01 Українська мова та література)",
        "educational_program_name": "Українська мова та література",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
    {
        "study_form": "OVER_DISTANCE",
        "study_duration": 47,
        "type": "відкрита",
        "speciality": "035 Філологія (035.041 Германські мови та літератури (переклад включно), перша - англійська)",
        "educational_program_name": "Англійська та друга західноєвропейська мови і літератури",
        "faculty": "Навчально-методичний центр заочної та вечірньої форм навчання",
    },
]


def pretty_print(name, data):
    print(f"{name} = [")

    for row in data:
        print("    {")

        for key, value in row.items():
            if value:
                print(f"        '{key}': \"{value}\",")

        print("    },")

    print("]")


def add_field(name, value, list_of_dicts, var):
    for item in list_of_dicts:
        item[name] = value

    pretty_print(var, list_of_dicts)


add_field("level", "phd", json_phd_accreditation, "json_accreditation")
