# Generated by Django 5.0.3 on 2024-05-31 07:52

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbiturientRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patronymic')),
                ('phone_number', models.CharField(help_text='Write the phone number in the following form: +380123456789 (start with +, then area code, then the rest of the number)', max_length=13, validators=[django.core.validators.RegexValidator('^\\+\\d{10,13}$', 'Wrong phone number format')], verbose_name='Phone number')),
                ('living_address', models.TextField(verbose_name='Living address')),
                ('passport_serie', models.CharField(blank=True, help_text='If you have an ID card, leave this field empty. If you have a book-passport, then fill this field.', max_length=2, null=True, verbose_name='Passport serie')),
                ('passport_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Passport number')),
                ('passport_authority', models.TextField(blank=True, help_text='If you have an ID card, this field should contain numbers. If you have a book-passport, this field should contain a text (description).', null=True, verbose_name='Authority')),
                ('passport_issue_date', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Date of issue')),
                ('rntrc', models.IntegerField(blank=True, help_text="Registration number of the taxpayer's account card (a local equivalent of the taxpayer's identification number)", null=True, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='RNTRC')),
            ],
            options={
                'verbose_name': 'Abiturient representative',
                'verbose_name_plural': 'Abiturient representatives',
            },
        ),
        migrations.CreateModel(
            name='Abiturient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patronymic')),
                ('phone_number', models.CharField(help_text='Write the phone number in the following form: +380123456789 (start with +, then area code, then the rest of the number)', max_length=13, validators=[django.core.validators.RegexValidator('^\\+\\d{10,13}$', 'Wrong phone number format')], verbose_name='Phone number')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('birth_country', models.CharField(max_length=255, verbose_name='Birth country')),
                ('birth_town', models.CharField(max_length=255, verbose_name='Birth town')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality')),
                ('education_institution', models.CharField(max_length=255, verbose_name='Educational institution')),
                ('education_place', models.CharField(max_length=255, verbose_name='Education place')),
                ('education_end', models.DateField(verbose_name='Education end date')),
                ('work', models.TextField(blank=True, null=True, verbose_name='Work')),
                ('martial_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married')], verbose_name='Marital status')),
                ('foreign_language', models.CharField(blank=True, max_length=255, null=True, verbose_name='Foreign language')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('living_address', models.TextField(verbose_name='Living address')),
                ('registered_address', models.TextField(verbose_name='Registered address')),
                ('mother_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mother's last name")),
                ('mother_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mother's first name")),
                ('mother_patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mother's patronymic")),
                ('mother_phone_number', models.CharField(blank=True, help_text='Write the phone number in the following form: +380123456789 (start with +, then area code, then the rest of the number)', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{10,13}$', 'Wrong phone number format')], verbose_name="Mother's phone number")),
                ('father_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's last name")),
                ('father_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's first name")),
                ('father_patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's patronymic")),
                ('father_phone_number', models.CharField(blank=True, help_text='Write the phone number in the following form: +380123456789 (start with +, then area code, then the rest of the number)', max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{10,13}$', 'Wrong phone number format')], verbose_name="Father's phone number")),
                ('passport_serie', models.CharField(blank=True, help_text='If you have an ID card, leave this field empty. If you have a book-passport, then fill this field.', max_length=2, null=True, verbose_name='Passport serie')),
                ('passport_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Passport number')),
                ('passport_authority', models.TextField(blank=True, help_text='If you have an ID card, this field should contain numbers. If you have a book-passport, this field should contain a text (description).', null=True, verbose_name='Authority')),
                ('passport_issue_date', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Date of issue')),
                ('rntrc', models.IntegerField(blank=True, help_text="Registration number of the taxpayer's account card (a local equivalent of the taxpayer's identification number)", null=True, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='RNTRC')),
                ('representative', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abiturients.abiturientrepresentative', verbose_name='Representative')),
            ],
            options={
                'verbose_name': 'Abiturient',
                'verbose_name_plural': 'Abiturients',
            },
        ),
    ]
