# Generated by Django 4.2.4 on 2024-03-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiturient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Чоловік'), (2, 'Жінка')])),
                ('birth_date', models.DateField()),
                ('birth_country', models.CharField(max_length=255)),
                ('birth_town', models.CharField(max_length=255)),
                ('education', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('foreign_language', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('work', models.TextField()),
                ('registered_address', models.TextField()),
                ('living_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Домашній'), (2, 'Мобільний'), (3, 'Робочий')])),
                ('number', models.CharField(max_length=255)),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturients.abiturient')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Матір'), (2, 'Батько'), (3, 'Опікун')])),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturients.abiturient')),
            ],
        ),
    ]
