# Generated by Django 5.0.4 on 2024-06-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturientrepresentative',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
