# Generated by Django 5.0.3 on 2024-05-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abiturient',
            old_name='marital_status',
            new_name='martial_status',
        ),
    ]
