# Generated by Django 5.0.3 on 2024-05-31 08:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Date of birth'),
        ),
    ]
