# Generated by Django 5.0.3 on 2024-04-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abiturient',
            options={'verbose_name': 'abiturient', 'verbose_name_plural': 'abiturient.plural'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'family_member', 'verbose_name_plural': 'family_member.plural'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'phone', 'verbose_name_plural': 'phone.plural'},
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='birth_country',
            field=models.CharField(max_length=255, verbose_name='abiturient.birth_country'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='birth_date',
            field=models.DateField(verbose_name='abiturient.birth_date'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='birth_town',
            field=models.CharField(max_length=255, verbose_name='abiturient.birth_town'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='education',
            field=models.TextField(verbose_name='abiturient.education'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='generic.email'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='generic.first_name'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='foreign_language',
            field=models.CharField(max_length=255, verbose_name='generic.foreign_language'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='generic.last_name'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='living_address',
            field=models.TextField(verbose_name='abiturient.living_address'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='nationality',
            field=models.CharField(max_length=255, verbose_name='generic.nationality'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='patronymic',
            field=models.CharField(max_length=255, verbose_name='generic.patronymic'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='registered_address',
            field=models.TextField(verbose_name='abiturient.registered_address'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='sex',
            field=models.PositiveIntegerField(choices=[(1, 'generic.sex.male'), (2, 'generic.sex.female')], verbose_name='generic.sex'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='work',
            field=models.TextField(verbose_name='abiturient.work'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='abiturient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturients.abiturient', verbose_name='abiturient'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='generic.first_name'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='generic.last_name'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='patronymic',
            field=models.CharField(max_length=255, verbose_name='generic.patronymic'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='telephone',
            field=models.CharField(max_length=255, verbose_name='generic.telephone'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='type',
            field=models.IntegerField(choices=[(1, 'family_member.type.mother'), (2, 'family_member.type.father'), (3, 'family_member.type.other')], verbose_name='family_member.type'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='abiturient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturients.abiturient', verbose_name='abiturient'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=255, verbose_name='phone.number'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.IntegerField(choices=[(1, 'phone.type.home'), (2, 'phone.type.mobile'), (3, 'phone.type.work')], verbose_name='phone.type'),
        ),
    ]
