# Generated by Django 5.0.4 on 2024-06-13 09:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0002_abiturientrepresentative_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today, 'Date of birth cannot be in the future')], verbose_name='Date of birth'),
        ),
    ]
