# Generated by Django 5.0.3 on 2024-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0002_alter_abiturient_options_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='generic.nationality'),
        ),
    ]
