# Generated by Django 5.0.3 on 2024-04-04 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0003_alter_abiturient_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'abiturients.invalid_name_part')], verbose_name='generic.first_name'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='foreign_language',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('[^\\W\\d]+', 'generic.only_alpha')], verbose_name='generic.foreign_language'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'abiturients.invalid_name_part')], verbose_name='generic.last_name'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('[^\\W\\d]+', 'generic.only_alpha')], verbose_name='generic.nationality'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='patronymic',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'abiturients.invalid_name_part')], verbose_name='generic.patronymic'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'abiturients.invalid_name_part')], verbose_name='generic.first_name'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'abiturients.invalid_name_part')], verbose_name='generic.last_name'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='patronymic',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'abiturients.invalid_name_part')], verbose_name='generic.patronymic'),
        ),
    ]
