# Generated by Django 5.0.3 on 2024-04-05 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0005_alter_familymember_telephone_alter_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='number',
        ),
        migrations.AddField(
            model_name='phone',
            name='telephone',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator('\\d+', 'generic.only_numbers')], verbose_name='generic.telephone'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='telephone',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator('\\d+', 'generic.only_numbers')], verbose_name='generic.telephone'),
        ),
    ]
