# Generated by Django 5.0.3 on 2024-04-05 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0006_remove_phone_number_phone_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='telephone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('\\d+', 'generic.only_numbers')], verbose_name='generic.telephone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='telephone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('\\d+', 'generic.only_numbers')], verbose_name='generic.telephone'),
        ),
    ]
