# Generated by Django 5.0.3 on 2024-04-15 06:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0007_alter_familymember_telephone_alter_phone_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='birth_country',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='abiturient.birth_country'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='abiturient.birth_date'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='birth_town',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='abiturient.birth_town'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='generic.first_name'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='foreign_language',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.foreign_language'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='generic.last_name'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.nationality'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='patronymic',
            field=models.CharField(max_length=255, verbose_name='generic.patronymic'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='generic.first_name'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='generic.last_name'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='patronymic',
            field=models.CharField(max_length=255, verbose_name='generic.patronymic'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='telephone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('\\d+', 'generic.only_numbers'), django.core.validators.MinLengthValidator(9)], verbose_name='generic.telephone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='telephone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('\\d+', 'generic.only_numbers'), django.core.validators.MinLengthValidator(9)], verbose_name='generic.telephone'),
        ),
    ]
