# Generated by Django 5.0.3 on 2024-04-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0008_alter_abiturient_birth_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'country.plural',
            },
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='birth_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abiturients.country'),
        ),
    ]
