# Generated by Django 5.0.3 on 2024-04-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0009_country_alter_abiturient_birth_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='birth_country',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
