# Generated by Django 5.0.3 on 2024-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0010_alter_abiturient_birth_country_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturient',
            name='birth_country',
            field=models.CharField(max_length=255, verbose_name='abiturient.birth_country'),
        ),
    ]
