# Generated by Django 5.0.4 on 2024-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='only_for_contract',
            field=models.BooleanField(default=False, verbose_name='Only for contract offers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='only_for_full_time',
            field=models.BooleanField(default=False, verbose_name='Only for contract full-time offers'),
            preserve_default=False,
        ),
    ]
