# Generated by Django 5.0.4 on 2024-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_only_for_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='only_for_contract',
            field=models.BooleanField(default=False, verbose_name='Only for contract offers'),
        ),
        migrations.AlterField(
            model_name='document',
            name='only_for_full_time',
            field=models.BooleanField(default=False, verbose_name='Only for full-time offers'),
        ),
    ]
