# Generated by Django 5.0.3 on 2024-04-15 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W]| )+', 'generic.only_alpha')]),
        ),
    ]
