# Generated by Django 5.0.3 on 2024-04-22 09:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.full_name')),
                ('abbreviation', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.abbreviation')),
                ('cipher', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='generic.cipher')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculty.plural',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.name')),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='generic.code')),
                ('specialization', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='speciality.specialization')),
                ('end_of_accreditation', models.DateField(blank=True, null=True, verbose_name='speciality.end_of_accreditation')),
                ('educational_program_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='speciality.educational_program_name')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.faculty', verbose_name='faculty')),
            ],
            options={
                'verbose_name': 'speciality',
                'verbose_name_plural': 'speciality.plural',
            },
        ),
        migrations.CreateModel(
            name='UniversityOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_begin', models.DateField(verbose_name='university_offer.study_begin')),
                ('study_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='university_offer.study_duration')),
                ('level', models.PositiveIntegerField(choices=[(1, 'university_offer.level.bachelor'), (2, 'university_offer.level.master'), (3, 'university_offer.level.aspirant')], verbose_name='university_offer.level')),
                ('basis', models.PositiveIntegerField(choices=[(1, 'university_offer.basis.school')], default=1, verbose_name='university_offers.basis')),
                ('type', models.PositiveIntegerField(choices=[(1, 'university_offer.type.budget'), (2, 'university_offer.type.contract')], verbose_name='university_offer.type')),
                ('study_form', models.PositiveIntegerField(choices=[(1, 'university_offer.study_form.day'), (2, 'university_offer.study_form.over_distance'), (3, 'university_offer.study_form.evening')], verbose_name='university_offer.study_form')),
                ('ects', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='university_offer.ects')),
                ('year1_cost', models.PositiveIntegerField(default=0, verbose_name='university_offer.year1_cost')),
                ('year2_cost', models.PositiveIntegerField(default=0, verbose_name='university_offer.year2_cost')),
                ('year3_cost', models.PositiveIntegerField(default=0, verbose_name='university_offer.year3_cost')),
                ('year4_cost', models.PositiveIntegerField(default=0, verbose_name='university_offer.year4_cost')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.speciality', verbose_name='speciality')),
            ],
            options={
                'verbose_name': 'university_offer',
                'verbose_name_plural': 'university_offer.plural',
            },
        ),
    ]
