# Generated by Django 4.2.4 on 2024-03-29 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=255, unique=True)),
                ('cipher', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('specialization', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_of_accreditation', models.DateField(null=True)),
                ('educational_program_name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_begin', models.DateField()),
                ('study_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.PositiveIntegerField(choices=[(1, 'Бюджет'), (2, 'Контракт')])),
                ('study_form', models.PositiveIntegerField(choices=[(1, 'Денна'), (2, 'Заочна'), (3, 'Вечірня')])),
                ('ects', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.speciality')),
            ],
        ),
    ]
