# Generated by Django 5.0.4 on 2024-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='ruslanpopov1512@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
