# Generated by Django 5.0.4 on 2024-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='end_of_accreditation',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='end_of_accreditation',
            field=models.DateField(blank=True, null=True, verbose_name='speciality.end_of_accreditation'),
        ),
    ]
