# Generated by Django 5.0.3 on 2024-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityoffer',
            name='basis',
            field=models.PositiveIntegerField(choices=[(1, 'university_offer.basis.school')], default=1, verbose_name='university_offers.basis'),
        ),
    ]
