# Generated by Django 4.2.4 on 2024-03-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='end_of_accreditation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
