# Generated by Django 5.0.3 on 2024-05-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0002_remove_speciality_end_of_accreditation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalprogram',
            name='end_of_accreditation',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='cipher',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='specialization',
        ),
        migrations.AddField(
            model_name='speciality',
            name='specialization_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='speciality.specialization_code'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='specialization_name',
            field=models.IntegerField(blank=True, null=True, verbose_name='speciality.specialization_name'),
        ),
        migrations.AlterField(
            model_name='universityoffer',
            name='basis',
            field=models.PositiveIntegerField(choices=[(1, 'university_offer.basis.pzso'), (2, 'university_offer.basis.nrk_5'), (3, 'university_offer.basis.nrk_6_7')], verbose_name='university_offers.basis'),
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'university_offer.level.bachelor'), (2, 'university_offer.level.master'), (3, 'university_offer.level.aspirant')], verbose_name='educational_level')),
                ('end_date', models.DateField(verbose_name='accreditation.end_date')),
                ('number', models.PositiveIntegerField(verbose_name='accreditation.number')),
                ('serie', models.CharField(blank=True, max_length=2, null=True, verbose_name='accreditation.serie')),
                ('type', models.PositiveIntegerField(choices=[(1, 'accreditation.type.speciality'), (2, 'accreditation.type.educational_program')], verbose_name='accreditation.type')),
                ('educational_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.educationalprogram', verbose_name='educational_program')),
            ],
            options={
                'verbose_name': 'accreditation',
                'verbose_name_plural': 'accreditation.plural',
            },
        ),
    ]
