# Generated by Django 5.0.4 on 2024-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0002_speciality_specialization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityoffer',
            name='year1_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Year 1 cost (for Masters it is semester 1 cost)'),
        ),
        migrations.AlterField(
            model_name='universityoffer',
            name='year2_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Year 2 cost (for Masters it is semester 2 cost)'),
        ),
        migrations.AlterField(
            model_name='universityoffer',
            name='year3_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Year 3 cost (for Masters it is semester 3 cost)'),
        ),
        migrations.AlterField(
            model_name='universityoffer',
            name='year4_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Year 4 cost (for Masters it is semester 4 cost)'),
        ),
    ]
