# Generated by Django 5.0.3 on 2024-04-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0002_universityoffer_basis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityoffer',
            old_name='year1_const',
            new_name='year1_cost',
        ),
        migrations.RenameField(
            model_name='universityoffer',
            old_name='year2_const',
            new_name='year2_cost',
        ),
        migrations.RenameField(
            model_name='universityoffer',
            old_name='year3_const',
            new_name='year3_cost',
        ),
        migrations.RenameField(
            model_name='universityoffer',
            old_name='year4_const',
            new_name='year4_cost',
        ),
    ]
