# Generated by Django 4.2.4 on 2024-03-29 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0002_alter_speciality_end_of_accreditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='specialization',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
