# Generated by Django 5.0.3 on 2024-05-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0003_remove_educationalprogram_end_of_accreditation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='specialization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='speciality.specialization_name'),
        ),
    ]
