# Generated by Django 5.0.3 on 2024-04-15 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0004_alter_faculty_options_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='abbreviation',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.abbreviation'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='full_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.full_name'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='educational_program_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='speciality.educational_program_name'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('([^\\W\\d]| )+', 'generic.only_alpha')], verbose_name='generic.name'),
        ),
    ]
