# Generated by Django 5.0.3 on 2024-05-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_offers', '0004_alter_speciality_specialization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityoffer',
            name='study_form',
            field=models.PositiveIntegerField(choices=[(1, 'university_offer.study_form.day'), (2, 'university_offer.study_form.over_distance'), (3, 'university_offer.study_form.distance')], verbose_name='university_offer.study_form'),
        ),
    ]
