# Generated by Django 5.0.3 on 2024-04-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='inn',
            field=models.IntegerField(verbose_name='persons.inn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persons.person', verbose_name='persons.parent'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport_number',
            field=models.IntegerField(verbose_name='persons.passport_number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport_who_give',
            field=models.IntegerField(verbose_name='persons.passport_who_give'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(verbose_name='generic.telephone'),
        ),
    ]
