# Generated by Django 5.0.4 on 2024-04-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='passport_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='passport_serie',
            new_name='serie',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='passport_when_given',
            new_name='when_given',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='passport_who_give',
            new_name='who_give',
        ),
    ]
