# Generated by Django 5.0.3 on 2024-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_inn_alter_person_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport_serie',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='persons.passport_serie'),
        ),
    ]
