# Generated by Django 5.0.3 on 2024-04-26 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_rename_passport_number_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$')], verbose_name='persons.inn'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='serie',
            field=models.CharField(blank=True, help_text='passport.serie.help', max_length=2, null=True, verbose_name='persons.passport_serie'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(help_text='telephone.help', max_length=12, validators=[django.core.validators.RegexValidator('^\\+\\d{10,12}$', 'generic.only_numbers')], verbose_name='generic.telephone'),
        ),
    ]
