# Generated by Django 5.0.3 on 2024-04-29 07:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_passport_inn_alter_passport_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='inn',
            field=models.IntegerField(blank=True, help_text='persons.inn.help', null=True, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='persons.inn'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='persons.passport_number'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='when_given',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='persons.passport_when_given'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='who_give',
            field=models.TextField(blank=True, help_text='passport.who_give.help', null=True, verbose_name='persons.passport_who_give'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(help_text='telephone.help', max_length=13, validators=[django.core.validators.RegexValidator('^\\+\\d{10,13}$', 'generic.only_numbers')], verbose_name='generic.telephone'),
        ),
    ]
