# Generated by Django 4.2.4 on 2024-03-29 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abiturients', '0001_initial'),
        ('university_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.IntegerField(choices=[(1, 'Державне замовлення'), (2, 'Місцевого замовлення'), (3, 'Кошти юридичних та/або фізичних осіб'), (4, 'Пільгове')])),
                ('payment_frequency', models.IntegerField(choices=[(1, 'Щосеместрово'), (2, 'Щорічно'), (3, 'Щомісячно'), (4, 'Повна за весь період навчання')])),
                ('accepted_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abiturients.abiturient')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.universityoffer')),
            ],
        ),
    ]
