# Generated by Django 5.0.4 on 2024-06-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abiturients', '0001_initial'),
        ('university_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('payment_frequency', models.IntegerField(blank=True, choices=[(1, 'Each semester'), (2, 'Each year'), (3, 'Full payment')], null=True, verbose_name='Payment frequency')),
                ('accepted_year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Accepted year')),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abiturients.abiturient', verbose_name='Abiturient')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.universityoffer', verbose_name='University offer')),
            ],
            options={
                'verbose_name': 'Accepted offer',
                'verbose_name_plural': 'Accepted offers',
            },
        ),
    ]
