# Generated by Django 5.0.3 on 2024-04-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accepting_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedoffer',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(2, 'accepting_offers.payment_type.town'), (3, 'accepting_offers.payment_type.private'), (4, 'accepting_offers.payment_type.privileged')], null=True, verbose_name='accepting_offers.payment_type'),
        ),
    ]
