# Generated by Django 5.0.3 on 2024-04-03 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturients', '0002_alter_abiturient_options_alter_familymember_options_and_more'),
        ('accepting_offers', '0001_initial'),
        ('university_offers', '0004_alter_faculty_options_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedoffer',
            options={'verbose_name': 'accepted_offer', 'verbose_name_plural': 'accepted_offer.plural'},
        ),
        migrations.AlterField(
            model_name='acceptedoffer',
            name='abiturient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abiturients.abiturient', verbose_name='abiturient'),
        ),
        migrations.AlterField(
            model_name='acceptedoffer',
            name='accepted_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='accepting_offers.accepted_year'),
        ),
        migrations.AlterField(
            model_name='acceptedoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='generic.created_at'),
        ),
        migrations.AlterField(
            model_name='acceptedoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_offers.universityoffer', verbose_name='university_offer'),
        ),
        migrations.AlterField(
            model_name='acceptedoffer',
            name='payment_frequency',
            field=models.IntegerField(choices=[(1, 'accepting_offers.payment_frequency.every_semester'), (2, 'accepting_offers.payment_frequency.every_year'), (3, 'accepting_offers.payment_frequency.every_month'), (4, 'accepting_offers.payment_frequency.full')], verbose_name='accepting_offers.payment_frequency'),
        ),
        migrations.AlterField(
            model_name='acceptedoffer',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'accepting_offers.payment_type.governmental'), (2, 'accepting_offers.payment_type.town'), (3, 'accepting_offers.payment_type.private'), (4, 'accepting_offers.payment_type.privileged')], verbose_name='accepting_offers.payment_type'),
        ),
    ]
