# Generated by Django 5.0.4 on 2024-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accepting_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedoffer',
            name='payment_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Each semester'), (2, 'Each year'), (3, 'Full payment')], null=True, verbose_name='Payment frequency'),
        ),
    ]
