# Generated by Django 5.0.3 on 2024-04-04 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accepting_offers', '0002_alter_acceptedoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedoffer',
            name='accepted_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='accepting_offers.accepted_year'),
        ),
        migrations.AlterField(
            model_name='acceptedoffer',
            name='payment_frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'accepting_offers.payment_frequency.every_semester'), (2, 'accepting_offers.payment_frequency.every_year'), (3, 'accepting_offers.payment_frequency.every_month'), (4, 'accepting_offers.payment_frequency.full')], null=True, verbose_name='accepting_offers.payment_frequency'),
        ),
    ]
